version: "3"

services:

  #php server
  baka-database:
    image: mctekk/phalconphp:7.4
    volumes:
      - .:/app
      - ../../baka:/baka
    depends_on:
      - 'redis'
      - 'mysql'
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
        - "81:80"
    links:
        - baka-database
    volumes:
        - .:/app
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-network
      - public-network

  redis:
    image: 'redis:5.0.5-alpine'
    ports: 
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - local-network

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - local-network

  mysql:
    image: mariadb:10.4
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - '.env'
    volumes:
      - "db-data:/var/lib/mysql"
      - "./storage/ci/mysql.cnf:/etc/mysql/conf.d/kanvas.cnf"
    networks:
        - local-network

  rabbitmq:
    image: rabbitmq:3.7.16-management
    hostname: "rabbit"
    env_file:
      - '.env'
    labels:
      NAME: "rabbitmq1"
    volumes:
      - "rabbitsvolumns:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - local-network
  elasticsearch: # Elasticsearch Instance
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes: # Persist ES data in separate "esdata" volume
      - elastic-data:/usr/share/elasticsearch/data
      - elasticvolumes:/usr/share/elasticsearch/plugins
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "ES_JAVA_OPTS=-Xms4000m -Xmx4000m"
      - "ES_JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XshowSettings:vm"
      - discovery.type=single-node
    #command: ./bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-sql/opendistro_sql-1.6.0.0.zip #install opendistro sql plugin
    #command: ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/7.5.1.0/elasticsearch-sql-7.5.1.0.zip #install sql plugin
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    networks:
      - local-network

volumes:
  db-data:
  redis:
  rabbitsvolumns:
  elasticvolumes:
  elastic-data:

networks:
  local-network:
  public-network:
